# https://github.com/merbanan/rtl_433/blob/master/BUILDING.md
- name: install prereqs
  package:
    name:
    - git
    - libtool
    - libusb-1.0-0-dev
    - librtlsdr-dev
    - rtl-sdr
    - build-essential
    - autoconf
    - cmake
    - pkg-config

- name: Clone repo
  git:
    repo: https://github.com/merbanan/rtl_433.git
    dest: /root/rtl_433

- name: Make build folder
  file:
    path: /root/rtl_433/build
    state: directory

- name: Build and install
  shell: |
    set -e;
    cd /root/rtl_433/build;
    /usr/bin/cmake ..;
    /usr/bin/make;
    /usr/bin/make install;
  args:
    creates: /usr/local/bin/rtl_433

- name: Install mosquitto-clients
  package:
    name: mosquitto-clients

- name: Create run shell script
  template:
    dest: /root/run_433.sh
    mode: "0755"
    src: resources/run_433.sh
